# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/
version: '3.8'

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:

  # create database container
  # https://blog.christian-schou.dk/creating-and-running-a-mysql-database-with-docker-compose/ 
  db:
    container_name: moviebase-database
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    hostname: database
    ports:
    - "3333:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_database:/var/lib/mysql
      - ./database/:/docker-entrypoint-initdb.d

  api:
    container_name: moviebase-api
    build:
      context: ./api
    env_file:
      - .env 
    volumes:
      - "./api:/app"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=80
  
  frontend:
    container_name: moviebase-frontend
    restart: always
    build:
      context: ./frontend
    volumes:
      - "./frontend/src:/app/src"
    environment:
      - PORT=80
  
  proxy:
    container_name: moviebase-nginx
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80
    depends_on:
      - api
      - frontend
  
volumes:
  mysql_database:
